"""The two tools the chat LLM can call. This is agentic RAG, not naive RAG:
`search_similar` handles "why"/"which" questions via semantic search;
`run_aggregate_query` handles "how much"/"how many" questions via a
constrained, parameterized query — never free-form SQL generated by the
model, which would be both a correctness risk (LLMs are bad at exact
aggregation) and an injection risk.
"""

from datetime import date
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, Field
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.chat.embeddings import embed
from app.models import Category, Expense, KnowledgeChunk

SEARCH_SIMILAR_SCHEMA = {
    "type": "function",
    "function": {
        "name": "search_similar",
        "description": (
            "Semantic search over the user's own expenses and anomaly alerts. "
            "Use for 'why'/'which'/'find' questions — e.g. 'why was I flagged "
            "last week', 'find my software subscription expenses'."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Natural-language search query"},
            },
            "required": ["query"],
        },
    },
}

RUN_AGGREGATE_QUERY_SCHEMA = {
    "type": "function",
    "function": {
        "name": "run_aggregate_query",
        "description": (
            "Numeric aggregation over the user's own expenses — totals, counts, "
            "or averages, optionally filtered by category and/or date range. Use "
            "for 'how much'/'how many'/'average' questions."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "aggregation": {"type": "string", "enum": ["sum", "count", "avg"]},
                "category_name": {
                    "type": ["string", "null"],
                    "description": "Exact category name to filter by, or null for all categories",
                },
                "start_date": {
                    "type": ["string", "null"],
                    "description": "ISO date (YYYY-MM-DD) lower bound, or null",
                },
                "end_date": {
                    "type": ["string", "null"],
                    "description": "ISO date (YYYY-MM-DD) upper bound, or null",
                },
            },
            "required": ["aggregation"],
        },
    },
}


async def search_similar(db: Session, user_id: int, query: str, k: int = 5) -> list[str]:
    vector = await embed(query)
    if vector is None:
        return []
    stmt = (
        select(KnowledgeChunk.content)
        .where(KnowledgeChunk.user_id == user_id)
        .order_by(KnowledgeChunk.embedding.cosine_distance(vector))
        .limit(k)
    )
    return list(db.execute(stmt).scalars().all())


class AggregateArgs(BaseModel):
    aggregation: Literal["sum", "count", "avg"]
    category_name: str | None = None
    start_date: date | None = None
    end_date: date | None = None


def run_aggregate_query(db: Session, user_id: int, args: AggregateArgs) -> dict:
    agg_fn = {"sum": func.sum, "count": func.count, "avg": func.avg}[args.aggregation]
    stmt = select(agg_fn(Expense.amount)).where(Expense.user_id == user_id)

    if args.category_name:
        stmt = stmt.join(Category, Expense.category_id == Category.id).where(
            Category.name.ilike(args.category_name)
        )
    if args.start_date:
        stmt = stmt.where(Expense.occurred_at >= args.start_date)
    if args.end_date:
        stmt = stmt.where(Expense.occurred_at <= args.end_date)

    result = db.execute(stmt).scalar()
    value = float(result) if isinstance(result, Decimal) else (result or 0)
    return {"aggregation": args.aggregation, "result": value, "filters": args.model_dump(mode="json")}
